
from rich.live import Live #(Source:https://rich.readthedocs.io/en/stable/reference/live.html)
from time import sleep
from zchar import monster5,monster7,monster131,monster132,monster133,monster134
from zmonster_alien import monster10_6,monster10_7,monster10_8,monster10_9,monster10,monster10_5,monster10_10,monster10_4
from zboss import monster1_1, monster2_1,monster2_1_1,monster3_1,monster4_1,monster5_1,monster6_1,monster7_1,monster8_1,monster9_1,monster10_1_boss
from zhero import herov1,herov2,herov3,herov4,herov5,herov6,herov7,herov8
from zarrowattacks import b11,b21_1,b21,b31,b41,b51,b61,b71,b81,b91,b91_3,bht,bh1,bh2,bh3,bh4,bh5,bh6,bh7,bh8,bh9,b71_def,b81_def1,b81_def2,b81_def3,b81_def4,b81_def5
from zfireball_attack import bha1,bha2,bha3,bha4,bha5,bha6
from thunder import bts1_1,bts1_2,bts1_3,bts2,bts3,bts4,bts5,bts6,bts2_1
from zhail import b41h,b51h,b61h,b71h,b81h,b91h,b91_3h,bhth,b71_1h,b81_1h,b91_1h,b91_3_1h,bht_1h
from zpoison import b41w,b51w,b61w,b71w,b81w,b91w,b91_3w,bhtw,b71_1w,b81_1w,b91_3_1w,bht_1w
from zbeast import bha1a,bha2a,bha3a,bha4a,bha5a,bha6a,bha7a,bha8a,bha9a,bha10a,bha11a,bha12a,bha13a,bha14a,bha15a,bha16a,bha11a_,bha4am2,bha4am3,bha4am4,bha3a1,bha3a2
from unicorn import bha3au,bha4au,bha5au,bha6au,bha7au,bha8au,bha9au,bha10au,bha11au,bha11a_u,bha12au,bha13au,bha14au,bha15au,bha16au
from zfire import b41hf, b51hf, b61hf, b71_1hf, b81_1hf,b91_3_1hf
from win import win1,win2,win3,win4

def win():
    for _ in range(20):
        with Live(win1, refresh_per_second=10, screen=True) as live:
            sleep(0.1)
            live.update(win2)
            sleep(0.1)
            live.update(win3)
            sleep(0.1)
            live.update(win4)
            sleep(0.1)
#win()



def poison_att():
    for _ in range(2):
        with Live(b11, refresh_per_second=10, screen=True) as live:
            sleep(0.5)
            live.update(b21_1)
            sleep(0.2)
            live.update(b21)
            sleep(0.4)
            live.update(b31)
            sleep(0.5)
            live.update(b41w)
            sleep(0.6)
            live.update(b51w)
            sleep(0.1)
            live.update(b61w)
            sleep(0.1)
            live.update(b71_1w)
            sleep(0.1)
            live.update(b81_1w)
            sleep(0.2)
            live.update(b91_3_1w)
            sleep(0.3)
            #transition scene
            live.update(bht_1w)
            sleep(0.4)
#poison_att()
def fire_att():
    for _ in range(2):
        with Live(b11, refresh_per_second=10, screen=True) as live:
            sleep(0.5)
            live.update(b21_1)
            sleep(0.2)
            live.update(b21)
            sleep(0.4)
            live.update(b31)
            sleep(0.5)
            live.update(b41hf)
            sleep(0.6)
            live.update(b51hf)
            sleep(0.1)
            live.update(b61hf)
            sleep(0.1)
            live.update(b71_1hf)
            sleep(0.1)
            live.update(b81_1hf)
            sleep(0.2)
            live.update(b91_3_1hf)
            sleep(0.3)
            #transition scene
            live.update(bht_1h)
            sleep(0.4)
#fire_att()
def unicorn():
    for _ in range(1):
        with Live(b11, refresh_per_second=10, screen=True) as live:
            sleep(0.3)
            live.update(bha1a)
            sleep(0.3)
            live.update(bha2a)
            sleep(0.3)
            live.update(bha3au)
            sleep(0.3)
            live.update(bha4au)
            sleep(0.3)
            live.update(bha5au)
            sleep(0.3)
            live.update(bha6au)
            sleep(0.3)
            live.update(bha7au)
            sleep(0.3)
            live.update(bha8au)
            sleep(0.3)
            live.update(bha9au)
            sleep(0.3)
            live.update(bha10au)
            sleep(0.3)
            live.update(bha11au)
            sleep(0.3)
            live.update(bha11a_u)
            sleep(0.3)
            live.update(bha12au)
            sleep(0.3)
            live.update(bha13au)
            sleep(0.3)
            live.update(bha14au)
            sleep(0.3)
            live.update(bha15au)
            sleep(0.3)
            live.update(bha16au)
            sleep(0.2)

#unicorn()

def pegasus():
    for _ in range(1):
        with Live(b11, refresh_per_second=10, screen=True) as live:
            sleep(0.3)
            live.update(bha1a)
            sleep(0.3)
            live.update(bha2a)
            sleep(0.3)
            live.update(bha3a)
            sleep(0.3)
            live.update(bha3a1)
            sleep(0.3)
            live.update(bha3a2)
            sleep(0.3)
            live.update(bha4a)
            sleep(0.3)
            live.update(bha4am2)
            sleep(0.3)
            live.update(bha4am3)
            sleep(0.3)
            live.update(bha4am4)
            sleep(0.3)
            live.update(bha5a)
            sleep(0.3)
            live.update(bha6a)
            sleep(0.3)
            live.update(bha7a)
            sleep(0.3)
            live.update(bha8a)
            sleep(0.3)
            live.update(bha9a)
            sleep(0.3)
            live.update(bha10a)
            sleep(0.2)
            live.update(bha11a)
            sleep(0.2)
            live.update(bha11a_)
            sleep(0.2)
            live.update(bha12a)
            sleep(0.2)
            live.update(bha13a)
            sleep(0.2)
            live.update(bha14a)
            sleep(0.2)
            live.update(bha15a)
            sleep(0.2)
            live.update(bha16a)
            sleep(0.2)
#pegasus()
def hail_att_def():
    for _ in range(3):
        with Live(b11, refresh_per_second=10, screen=True) as live:
            sleep(0.5)
            live.update(b21_1)
            sleep(0.2)
            live.update(b21)
            sleep(0.4)
            live.update(b31)
            sleep(0.5)
            live.update(b41h)
            sleep(0.6)
            live.update(b51h)
            sleep(0.1)
            live.update(b61h)
            sleep(0.1)
            live.update(b71h)
            sleep(0.1)
            live.update(b81h)
            sleep(0.2)
            live.update(b91_3h)
            sleep(0.3)
            #transition scene
            live.update(bhth)
            sleep(0.4)
#hail_att_def()
def poison_att_def():
    for _ in range(2):
        with Live(b11, refresh_per_second=10, screen=True) as live:
            sleep(0.5)
            live.update(b21_1)
            sleep(0.2)
            live.update(b21)
            sleep(0.4)
            live.update(b31)
            sleep(0.5)
            live.update(b41w)
            sleep(0.6)
            live.update(b51w)
            sleep(0.1)
            live.update(b61w)
            sleep(0.1)
            live.update(b71w)
            sleep(0.1)
            live.update(b81w)
            sleep(0.2)
            live.update(b91_3w)
            sleep(0.3)
            #transition scene
            live.update(bhtw)
            sleep(0.4)
#poison_att_def()
def hail_att():
    for _ in range(2):
        with Live(b11, refresh_per_second=10, screen=True) as live:
            sleep(0.5)
            live.update(b21_1)
            sleep(0.2)
            live.update(b21)
            sleep(0.4)
            live.update(b31)
            sleep(0.5)
            live.update(b41h)
            sleep(0.6)
            live.update(b51h)
            sleep(0.1)
            live.update(b61h)
            sleep(0.1)
            live.update(b71_1h)
            sleep(0.1)
            live.update(b81_1h)
            sleep(0.2)
            live.update(b91_3_1h)
            sleep(0.3)
            #transition scene
            live.update(bht_1h)
            sleep(0.4)
#hail_att()

def thunder():
    for _ in range(2):
        with Live(bts1_1, refresh_per_second=10, screen=True) as live:
            sleep(0.3)
            live.update(bts1_2)
            sleep(0.3)
            live.update(bts1_3)
            sleep(0.2)
            live.update(bts2_1)
            sleep(0.12)
            live.update(bts3)
            sleep(0.12)
            live.update(bts4)
            sleep(0.12)
            live.update(bts5)
            sleep(0.12)
            live.update(bts6)
            sleep(0.5)


#thunder()


def meteor():
    for _ in range(2):
        with Live(b11, refresh_per_second=10, screen=True) as live:
            sleep(0.3)
            live.update(bha1)
            sleep(0.3)
            live.update(bha2)
            sleep(0.3)
            live.update(bha3)
            sleep(0.3)
            live.update(bha4)
            sleep(0.3)
            live.update(bha5)
            sleep(0.3)
            live.update(bha6)
            sleep(0.3)
#meteor()
def battle3():
    for _ in range(2):
        with Live(b11, refresh_per_second=10, screen=True) as live:
            sleep(0.5)
            live.update(b21_1)
            sleep(0.2)
            live.update(b21)
            sleep(0.4)
            live.update(b31)
            sleep(0.5)
            live.update(b41)
            sleep(0.6)
            live.update(b51)
            sleep(0.1)
            live.update(b61)
            sleep(0.1)
            live.update(b71)
            sleep(0.1)
            live.update(b81)
            sleep(0.2)
            live.update(b91_3)
            sleep(0.3)
            #transition scene
            live.update(bht)
            sleep(0.4)
            #hero strikes now
            live.update(bh1)
            sleep(0.4)
            live.update(bh2)
            sleep(0.4)
            live.update(bh3)
            sleep(0.2)
            live.update(bh4)
            sleep(0.2)
            live.update(bh5)
            sleep(0.2)
            live.update(bh6)
            sleep(0.2)
            live.update(bh7)
            sleep(0.2)
            live.update(bh8)
            sleep(0.2)
            live.update(bh9)
            sleep(0.7)


#battle3()

def defend():
    for _ in range(2):
        with Live(b11, refresh_per_second=10, screen=True) as live:
            sleep(0.5)
            live.update(b21_1)
            sleep(0.2)
            live.update(b21)
            sleep(0.4)
            live.update(b31)
            sleep(0.5)
            live.update(b41)
            sleep(0.6)
            live.update(b51)
            sleep(0.1)
            live.update(b61)
            sleep(0.1)
            live.update(b71)
            sleep(0.1)
            live.update(b81)
            sleep(0.2)
            live.update(b91_3)
            sleep(0.3)
            #transition scene
            live.update(bht)
            sleep(0.4)


def battle_def():
    for _ in range(2):
        with Live(b11, refresh_per_second=10, screen=True) as live:
            sleep(0.5)
            live.update(b21_1)
            sleep(0.2)
            live.update(b21)
            sleep(0.4)
            live.update(b31)
            sleep(0.5)
            live.update(b41)
            sleep(0.6)
            live.update(b51)
            sleep(0.1)
            live.update(b61)
            sleep(0.1)
            live.update(b71_def)
            sleep(0.3)
            live.update(b81_def1)
            sleep(0.3)
            live.update(b81_def2)
            sleep(0.3)
            live.update(b81_def3)
            sleep(0.3)
            live.update(b81_def4)
            sleep(0.3)
            live.update(b81_def5)
            sleep(0.2)

            #Hero strike begins
            live.update(bh2)
            sleep(0.4)
            live.update(bh3)
            sleep(0.2)
            live.update(bh4)
            sleep(0.2)
            live.update(bh5)
            sleep(0.2)
            live.update(bh6)
            sleep(0.2)
            live.update(bh7)
            sleep(0.2)
            live.update(bh8)
            sleep(0.2)
            live.update(bh9)
            sleep(0.7)
#battle_def()
def hero_att():
    for _ in range(2):
        with Live(b11, refresh_per_second=10, screen=True) as live:
            live.update(bh2)
            sleep(0.4)
            live.update(bh3)
            sleep(0.2)
            live.update(bh4)
            sleep(0.2)
            live.update(bh5)
            sleep(0.2)
            live.update(bh6)
            sleep(0.2)
            live.update(bh7)
            sleep(0.2)
            live.update(bh8)
            sleep(0.2)
            live.update(bh9)
            sleep(0.7)



def bomber():
    for _ in range(30):
        with Live(monster5, refresh_per_second=10,screen=True) as live:
            sleep(0.4)
            live.update(monster7)
            sleep(0.2)
            live.update(monster131)
            sleep(0.3)
            live.update(monster132)
            sleep(0.3)
            live.update(monster133)
            sleep(0.3)
            live.update(monster134)
            sleep(0.4)

#bomber()


def alien():
    for _ in range(30):
        with Live(monster10_4, refresh_per_second=10) as live:
            sleep(0.6)
            live.update(monster10_5)
            sleep(0.6)
            live.update(monster10_6)
            sleep(0.6)
            live.update(monster10_7)
            sleep(0.6)
            live.update(monster10_8)
            sleep(0.6)
            live.update(monster10_9)
            sleep(0.6)
            live.update(monster10_10)
            sleep(0.6)
            live.update(monster10)
            sleep(3)
#alien()
def boss():
    for _ in range(30):
        with Live(monster1_1, refresh_per_second=10,screen=True) as live:
            sleep(0.4)
            live.update(monster2_1)
            sleep(0.6)
            live.update(monster2_1_1)
            sleep(0.6)
            live.update(monster3_1)
            sleep(0.6)
            live.update(monster4_1)
            sleep(0.1)
            live.update(monster5_1)
            sleep(0.1)
            live.update(monster6_1)
            sleep(0.1)
            live.update(monster7_1)
            sleep(0.2)
            live.update(monster8_1)
            sleep(0.2)
            live.update(monster9_1)
            sleep(0.4)
#boss()

def boss2():
    for _ in range(3):
        with Live(monster1_1, refresh_per_second=10, screen=True) as live:
            sleep(0.4)
            live.update(monster2_1)
            sleep(0.6)
            live.update(monster2_1_1)
            sleep(0.6)
            live.update(monster3_1)
            sleep(0.6)
            live.update(monster4_1)
            sleep(0.1)
            live.update(monster5_1)
            sleep(0.1)
            live.update(monster6_1)
            sleep(0.1)
            live.update(monster7_1)
            sleep(0.2)
            live.update(monster8_1)
            sleep(0.2)
            live.update(monster9_1)
            sleep(0.2)
            live.update(monster10_1_boss)
            sleep(0.6)

#boss2()

def hero():
    for _ in range(20):
        with Live(herov1, refresh_per_second=10, screen=True) as live:
            sleep(0.2)
            live.update(herov2)
            sleep(0.2)
            live.update(herov3)
            sleep(0.2)
            live.update(herov4)
            sleep(0.2)
            live.update(herov5)
            sleep(0.2)
            live.update(herov6)
            sleep(0.2)
            live.update(herov7)
            sleep(0.15)
            live.update(herov8)
            sleep(0.5)
#hero()
#print(alien(),bomber())
#print("🔥 Explosion Incoming!")
#time.sleep(2)
#os.system('cls' if os.name == 'nt' else 'clear')  # Clear screen (Windows/Linux)
#print("💨 It's gone...")
#console = Console()
